Display multiple currencies
Androz2091/discord-data-package-explorer pull request #65
Opened 2022-07-18 14:33 UTC by Midokuni

Since the payments can be made in multiple currencies this shows breakdown of totals per currency in the stats instead of treating everything as USD.

2022-07-18 20:14 UTC, Androz2091 reviewed
Thank you for your PR! Please use let instead of var and space between things like "=>" or "/" to match the code style

2022-07-18 20:14 UTC, Androz2091 requested changes
see comment above

2022-07-19 01:40 UTC, Midokuni commented
Addressed

2024-05-26 07:24 UTC, Androz2091 approved these changes
LGTM. Thank you for your PR

2024-05-26 07:24 UTC, merged